CREATE TABLE METHOD
(
    METHOD_PK INTEGER PRIMARY KEY AUTOINCREMENT,
    METHOD_NM TEXT NOT NULL UNIQUE
);

CREATE TABLE ROLE
(
    ROLE_PK INTEGER PRIMARY KEY,
    ROLE_NM TEXT NOT NULL UNIQUE
);

CREATE INDEX IDX_ROLE_NM
    ON ROLE (ROLE_NM);

CREATE TABLE ROUTE_OPTION
(
    ROUTE_OPTION_PK INTEGER PRIMARY KEY AUTOINCREMENT,
    ROUTE_OPTION_NM TEXT NOT NULL UNIQUE
);

CREATE TABLE SERVICE
(
    SERVICE_PK INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_NM TEXT NOT NULL UNIQUE,
    SERVICE_DOMAIN TEXT NOT NULL UNIQUE,
    SERVICE_INDEX TEXT DEFAULT 'none'
);

CREATE TABLE API_ROUTE
(
    API_ROUTE_PK INTEGER PRIMARY KEY AUTOINCREMENT,
    API_ROUTE_PATH TEXT NOT NULL,
    METHOD_METHOD_PK INTEGER NOT NULL,
    ROLE_ROLE_PK INTEGER,
    SERVICE_SERVICE_PK INTEGER NOT NULL,
    ROUTE_OPTION_ROUTE_OPTION_PK INTEGER DEFAULT 1 NOT NULL,
    PATH_VARIABLE TEXT,
    FOREIGN KEY (ROUTE_OPTION_ROUTE_OPTION_PK) REFERENCES ROUTE_OPTION (ROUTE_OPTION_PK),
    FOREIGN KEY (METHOD_METHOD_PK) REFERENCES METHOD (METHOD_PK),
    FOREIGN KEY (ROLE_ROLE_PK) REFERENCES ROLE (ROLE_PK),
    FOREIGN KEY (SERVICE_SERVICE_PK) REFERENCES SERVICE (SERVICE_PK)
);

CREATE INDEX IDX_ROUTE_OPTION_ROUTE_OPTION_PK
    ON API_ROUTE (ROUTE_OPTION_ROUTE_OPTION_PK);

CREATE INDEX IDX_ROUTE_METHOD1
    ON API_ROUTE (METHOD_METHOD_PK);

CREATE INDEX IDX_ROUTE_ROLE1
    ON API_ROUTE (ROLE_ROLE_PK);

CREATE INDEX IDX_ROUTE_SERVICE1
    ON API_ROUTE (SERVICE_SERVICE_PK);